---
abstract: 'parse POD from tree form'
author:
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
build_requires:
  Module::Build: 0
  Pod::Simple::DumpAsXML: 0
  Test::More: 0
  perl: 5.006
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0.36
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Simple-FromTree
provides:
  Pod::Simple::FromTree:
    file: lib/Pod/Simple/FromTree.pm
    version: 0.000
requires:
  Pod::Simple: 0
  parent: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.000
